### ISSUE TITLE
Weapontypes and Reloading

### ISSUE THREAD

**Issue by aeypex** [Forpex/LogisticArena#10]
- Reichweite
- Nachladezeit
- Ammocounts
- Accuracy nicht random. wird vom schaden abgezogen
muessen angepasst werden.
Rail (inf, 2sec, 10?, 30%)
LG (2-5, 50ms, 10*20, 30-40%)
Rocket (0-1, 1sec, 10-20, 60%)
Waffe wird abstract class?

**Comment by 4rasago** [comment]
0.5 * 80 * 0.6 = 24 (RG DPS)
20 * 6 * 0.35 = 42 (LG DPS)
1 * 100 * 0.7 = 70 (RL DPS)

**Comment by 4rasago** [comment]
oder 70 / 30 / 50

**Comment by aeypex** [comment]
Checking: Rocket > LG > RG > MG
MG infinite ammo.

**Comment by 4rasago** [comment]
boolean rocket, lg, rail;
int distance, damage;

if (distance < 2) {
  if (rocket) damage = 70 - (distance * 10);
} else if (distance < 4) {
  if (lg) damage = 50 - (distance * 10);
} else if (distance < 6) {
  if (rail) damage = 30;
} else damage = 20;

**Comment by aeypex** [comment]
Hey, lass uns vllt lieber die Shotgun nehmen. Ist auch eine Ikone im Shooterbereich.
Die limitierte Reichweite passt einfach besser.

**Comment by 4rasago** [comment]
das wären dann nur hitscan waffen. außerdem dachte ich wir orientieren uns an quake (3/live).

**Comment by aeypex** [comment]
Ja leider. Der Raketenwerfer lebt gewaltig von der richtigen positionierung der schüsse. Also noch ein Level des Timings.
Wenn der user bestimmen könnte, wo der schuss landet und dann die rakete selbstständig dorthin fliegt, dann und nur dann wäre dies dem Raketenwerfer würdig.

**Comment by 4rasago** [comment]
ein argument trotzdem raketen zu nehmen wären die visuals. explosionen um die spieler rum wären eine coolere illustration als nur shotgun sound effekte und ein paar funken oder so. wenn du trotzdem auf shotgun bestehst, gehe ich da mit. ich gebe das nur zu bedenken.
