### ISSUE TITLE
Avatar Death

### ISSUE THREAD

**Issue by aeypex** [Forpex/LogisticArena#11]
Health drops to 0.
Need to decide and implement how respawns and score is done.

**Comment by 4rasago** [comment]
Meine Lieblingsvariante ist die Eine-Zahl-Abrechnung. Statt zwei Werten (Score Spieler 1 zu Score Spieler 2) wird pro Spieler nur der Unterschied angezeigt: Frags (=Gegnertode im Duell) minus eigene Tode.
Quake Live Status: 5 zu 3
Unterschied: +2

**Comment by 4rasago** [comment]
Respawn: Mindestdistanz festlegen und dann Zufall

**Comment by aeypex** [comment]
Score, wie waere es, das ganze in +% anzugeben?
Also 5 zu 3 ist dann +66%.

**Comment by 4rasago** [comment]
nein, deutlicher unterschied zwischen 5-3 und 10-6 bei taktischen überlegungen.
das wichtige ist der absolute unterschied.

**Comment by aeypex** [comment]
So, ich habe jetzt die punkte und den spawnmechanismus realisiert.
Den absoluten unterschied anzugeben, ist glaube ich nicht schwer: 

- [ ] Einfach score.getAbsoluteDifference(clientID); implementieren.
