### ISSUE TITLE
implement TurnAround on edges

### ISSUE THREAD

**Issue by aeypex** [Forpex/LogisticArena#13]
i wont implement it yet, but it might become useful later.

**Comment by 4rasago** [comment]
glaube absolut notwendig. stell dir vor du willst in den nahkampf gehen und dann laufen die beiden spieler aneinander vorbei und tauschen quasi plätze.
stehen bleiben und umdrehen sind unverzichtbar.

**Comment by aeypex** [comment]
ok verstehe. Wird gemacht. Ist auch jetzt, da wir drueber gesprochen haben, nicht mehr sooo schwer.
ich werde das ganz als UserStory nochmal aus dem Discord hier hin posten.
