### ISSUE TITLE
How does a Client choose a path?

### ISSUE THREAD

**Issue by aeypex** [Forpex/LogisticArena#2]
Richtung auswaehlen....?

**Comment by 4rasago** [comment]
1st phase: Click on paths
2nd phase: Add "mobile" support (touch screen press instead of click)
Hypothetical 3rd phase: Add analog stick support

**Comment by aeypex** [comment]
ill start simple: i ask client for input of id for edge. wrong input is staying.
so the first simple client can be of console descend for testing purposes.
